=== cea-hpc/mpc/mpc/MPC_Config/editor/config/mpc-config.xsd
<?xml version="1.0"?>
<!--
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - VALAT Sebastien sebastien.valat@cea.fr                           #
#   - AUTOMATIC GENERATION                                             #
#                                                                      #
########################################################################
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="size">
  </xs:element>
  <xs:element name="funcptr">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_allocator">
    <xs:all>
      <xs:element minOccurs="0" name="numa_migration" type="xs:boolean"/>
      <xs:element minOccurs="0" name="realloc_factor" type="xs:integer"/>
      <xs:element minOccurs="0" name="realloc_threashold">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+[\s]?[K|M|G|T|P]?B" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="numa" type="xs:boolean"/>
      <xs:element minOccurs="0" name="strict" type="xs:boolean"/>
      <xs:element minOccurs="0" name="keep_mem">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+[\s]?[K|M|G|T|P]?B" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="keep_max">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+[\s]?[K|M|G|T|P]?B" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_launcher">
    <xs:all>
      <xs:element minOccurs="0" name="verbosity" type="xs:integer"/>
      <xs:element minOccurs="0" name="banner" type="xs:boolean"/>
      <xs:element minOccurs="0" name="autokill" type="xs:integer"/>
      <xs:element minOccurs="0" name="user_launchers" type="xs:string"/>
      <xs:element minOccurs="0" name="keep_rand_addr" type="xs:boolean"/>
      <xs:element minOccurs="0" name="disable_rand_addr" type="xs:boolean"/>
      <xs:element minOccurs="0" name="disable_mpc" type="xs:boolean"/>
      <xs:element minOccurs="0" name="thread_init">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="nb_task" type="xs:integer"/>
      <xs:element minOccurs="0" name="nb_process" type="xs:integer"/>
      <xs:element minOccurs="0" name="nb_processor" type="xs:integer"/>
      <xs:element minOccurs="0" name="nb_node" type="xs:integer"/>
      <xs:element minOccurs="0" name="launcher" type="xs:string"/>
      <xs:element minOccurs="0" name="max_try" type="xs:integer"/>
      <xs:element minOccurs="0" name="vers_details" type="xs:boolean"/>
      <xs:element minOccurs="0" name="profiling" type="xs:string"/>
      <xs:element minOccurs="0" name="enable_smt" type="xs:boolean"/>
      <xs:element minOccurs="0" name="share_node" type="xs:boolean"/>
      <xs:element minOccurs="0" name="restart" type="xs:boolean"/>
      <xs:element minOccurs="0" name="checkpoint" type="xs:boolean"/>
      <xs:element minOccurs="0" name="migration" type="xs:boolean"/>
      <xs:element minOccurs="0" name="report" type="xs:boolean"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_debugger">
    <xs:all>
      <xs:element minOccurs="0" name="colors" type="xs:boolean"/>
      <xs:element minOccurs="0" name="max_filename_size" type="xs:integer"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_net_driver_infiniband">
    <xs:all>
      <xs:element minOccurs="0" name="network_type" type="xs:integer"/>
      <xs:element minOccurs="0" name="adm_port" type="xs:integer"/>
      <xs:element minOccurs="0" name="verbose_level" type="xs:integer"/>
      <xs:element minOccurs="0" name="eager_limit" type="xs:integer"/>
      <xs:element minOccurs="0" name="buffered_limit" type="xs:integer"/>
      <xs:element minOccurs="0" name="qp_tx_depth" type="xs:integer"/>
      <xs:element minOccurs="0" name="qp_rx_depth" type="xs:integer"/>
      <xs:element minOccurs="0" name="cq_depth" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_sg_sq" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_sg_rq" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_inline" type="xs:integer"/>
      <xs:element minOccurs="0" name="rdma_resizing" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_rdma_connections" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_rdma_resizing" type="xs:integer"/>
      <xs:element minOccurs="0" name="init_ibufs" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_srq_ibufs_posted" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_srq_ibufs" type="xs:integer"/>
      <xs:element minOccurs="0" name="srq_credit_limit" type="xs:integer"/>
      <xs:element minOccurs="0" name="srq_credit_thread_limit" type="xs:integer"/>
      <xs:element minOccurs="0" name="size_ibufs_chunk" type="xs:integer"/>
      <xs:element minOccurs="0" name="init_mr" type="xs:integer"/>
      <xs:element minOccurs="0" name="size_mr_chunk" type="xs:integer"/>
      <xs:element minOccurs="0" name="mmu_cache_enabled" type="xs:integer"/>
      <xs:element minOccurs="0" name="mmu_cache_entries" type="xs:integer"/>
      <xs:element minOccurs="0" name="steal" type="xs:integer"/>
      <xs:element minOccurs="0" name="quiet_crash" type="xs:integer"/>
      <xs:element minOccurs="0" name="async_thread" type="xs:integer"/>
      <xs:element minOccurs="0" name="wc_in_number" type="xs:integer"/>
      <xs:element minOccurs="0" name="wc_out_number" type="xs:integer"/>
      <xs:element minOccurs="0" name="rdma_depth" type="xs:integer"/>
      <xs:element minOccurs="0" name="rdma_dest_depth" type="xs:integer"/>
      <xs:element minOccurs="0" name="low_memory" type="xs:boolean"/>
      <xs:element minOccurs="0" name="rdvz_protocol" type="user_type_ibv_rdvz_protocol"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:simpleType name="user_type_ibv_rdvz_protocol">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IBV_RDVZ_WRITE_PROTOCOL"/>
      <xs:enumeration value="IBV_RDVZ_READ_PROTOCOL"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_net_driver_tcp">
    <xs:all>
      <xs:element minOccurs="0" name="fake_param" type="xs:integer"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_net_driver">
    <xs:choice>
      <xs:element name="infiniband" type="user_type_net_driver_infiniband"/>
      <xs:element name="tcp" type="user_type_net_driver_tcp"/>
      <xs:element name="tcpoib" type="user_type_net_driver_tcp"/>
    </xs:choice>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_net_driver_config">
    <xs:all>
      <xs:element minOccurs="0" name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="driver" type="user_type_net_driver"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_net_cli_option">
    <xs:all>
      <xs:element minOccurs="0" name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="rails">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="rail" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_net_rail">
    <xs:all>
      <xs:element minOccurs="0" name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="device" type="xs:string"/>
      <xs:element minOccurs="0" name="topology" type="xs:string"/>
      <xs:element minOccurs="0" name="config" type="xs:string"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_networks">
    <xs:all>
      <xs:element minOccurs="0" name="configs">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="config" type="user_type_net_driver_config"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="rails">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="rail" type="user_type_net_rail"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="cli_options">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="cli_option" type="user_type_net_cli_option"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_inter_thread_comm">
    <xs:all>
      <xs:element minOccurs="0" name="barrier_arity" type="xs:integer"/>
      <xs:element minOccurs="0" name="broadcast_arity_max" type="xs:integer"/>
      <xs:element minOccurs="0" name="broadcast_max_size" type="xs:integer"/>
      <xs:element minOccurs="0" name="broadcast_check_threshold" type="xs:integer"/>
      <xs:element minOccurs="0" name="allreduce_arity_max" type="xs:integer"/>
      <xs:element minOccurs="0" name="allreduce_max_size" type="xs:integer"/>
      <xs:element minOccurs="0" name="allreduce_check_threshold" type="xs:integer"/>
      <xs:element minOccurs="0" name="collectives_init_hook">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_][0-9A-Za-z_]*"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_low_level_comm">
    <xs:all>
      <xs:element minOccurs="0" name="checksum">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="send_msg">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="notify_recv_msg">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="notify_matching_msg">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="notify_perform_msg">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="notify_idle_msg">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="notify_any_src_msg">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="^[A-Za-z_][0-9A-Za-z_]*$"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="network_mode" type="xs:string"/>
      <xs:element minOccurs="0" name="dyn_reordering" type="xs:boolean"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_mpc">
    <xs:all>
      <xs:element minOccurs="0" name="log_debug" type="xs:boolean"/>
      <xs:element minOccurs="0" name="hard_checking" type="xs:boolean"/>
      <xs:element minOccurs="0" name="buffering" type="xs:boolean"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_openmp">
    <xs:all>
      <xs:element minOccurs="0" name="vp" type="xs:integer"/>
      <xs:element minOccurs="0" name="schedule" type="xs:string"/>
      <xs:element minOccurs="0" name="nb_threads" type="xs:integer"/>
      <xs:element minOccurs="0" name="adjustment" type="xs:boolean"/>
      <xs:element minOccurs="0" name="nested" type="xs:boolean"/>
      <xs:element minOccurs="0" name="max_threads" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_alive_for_dyn" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_alive_for_guided" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_alive_sections" type="xs:integer"/>
      <xs:element minOccurs="0" name="max_alive_single" type="xs:integer"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_profiler">
    <xs:all>
      <xs:element minOccurs="0" name="file_prefix" type="xs:string"/>
      <xs:element minOccurs="0" name="append_date" type="xs:boolean"/>
      <xs:element minOccurs="0" name="color_stdout" type="xs:boolean"/>
      <xs:element minOccurs="0" name="level_colors">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="level" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="user_type_thread">
    <xs:all>
      <xs:element minOccurs="0" name="spin_delay" type="xs:integer"/>
      <xs:element minOccurs="0" name="interval" type="xs:integer"/>
      <xs:element minOccurs="0" name="kthread_stack_size">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+[\s]?[K|M|G|T|P]?B" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="modules">
    <xs:all>
      <xs:element minOccurs="0" name="allocator" type="user_type_allocator"/>
      <xs:element minOccurs="0" name="launcher" type="user_type_launcher"/>
      <xs:element minOccurs="0" name="debugger" type="user_type_debugger"/>
      <xs:element minOccurs="0" name="inter_thread_comm" type="user_type_inter_thread_comm"/>
      <xs:element minOccurs="0" name="low_level_comm" type="user_type_low_level_comm"/>
      <xs:element minOccurs="0" name="mpc" type="user_type_mpc"/>
      <xs:element minOccurs="0" name="openmp" type="user_type_openmp"/>
      <xs:element minOccurs="0" name="profiler" type="user_type_profiler"/>
      <xs:element minOccurs="0" name="thread" type="user_type_thread"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_mapping_selector_env">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_mapping_selectors">
    <xs:sequence>
      <xs:element name="env" type="static_part_mapping_selector_env" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_mapping_profiles">
    <xs:sequence>
      <xs:element name="profile" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_mapping">
    <xs:all>
      <xs:element name="selectors" type="static_part_mapping_selectors" minOccurs="0"/>
      <xs:element name="profiles" type="static_part_mapping_profiles" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_mappings">
    <xs:sequence>
      <xs:element name="mapping" type="static_part_mapping" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_profile">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="modules" type="modules" minOccurs="0"/>
      <xs:element name="networks" type="user_type_networks" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_profiles">
    <xs:sequence>
      <xs:element name="profile" type="static_part_profile" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:complexType name="static_part_mpc">
    <xs:sequence>
      <xs:element name="profiles" type="static_part_profiles" minOccurs="0"/>
      <xs:element name="mappings" type="static_part_mappings" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!-- ********************************************************* -->
  <xs:element name="mpc" type="static_part_mpc"/>
</xs:schema>

=== cea-hpc/mpc/mpc/MPC_Config/editor/config/config-small.xml
<?xml version='1.0'?>
<mpc xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='mpc-config.xsd'>
  <profiles>
    <profile>
      <name>default</name>
      <modules>
        <allocator>
          <numa_migration>false</numa_migration>
          <realloc_factor>2</realloc_factor>
          <realloc_threashold>50 GB</realloc_threashold>
          <numa>true</numa>
          <strict>false</strict>
          <keep_mem>500MB</keep_mem>
          <keep_max>8 MB</keep_max>
        </allocator>
        <launcher>
          <verbosity>0</verbosity>
          <banner>true</banner>
          <autokill>300</autokill>
          <user_launchers>default</user_launchers>
          <keep_rand_addr>true</keep_rand_addr>
          <disable_rand_addr>false</disable_rand_addr>
          <disable_mpc>false</disable_mpc>
          <thread_init>sctk_use_ethread_mxn</thread_init>
          <nb_task>1</nb_task>
          <nb_process>1</nb_process>
          <nb_processor>0</nb_processor>
          <nb_node>0</nb_node>
          <launcher>none</launcher>
          <max_try>10</max_try>
          <vers_details>false</vers_details>
          <profiling>none</profiling>
          <enable_smt>false</enable_smt>
          <share_node>false</share_node>
          <restart>false</restart>
          <checkpoint>false</checkpoint>
          <migration>false</migration>
          <report>false</report>
        </launcher>
        <debugger>
          <colors>true</colors>
          <max_filename_size>1024</max_filename_size>
        </debugger>
        <inter_thread_comm>
          <barrier_arity>8</barrier_arity>
          <broadcast_arity_max>32</broadcast_arity_max>
          <broadcast_max_size>1024</broadcast_max_size>
          <broadcast_check_threshold>512</broadcast_check_threshold>
          <allreduce_arity_max>8</allreduce_arity_max>
          <allreduce_max_size>1024</allreduce_max_size>
          <allreduce_check_threshold>8192</allreduce_check_threshold>
          <collectives_init_hook>sctk_collectives_init_opt_messages</collectives_init_hook>
        </inter_thread_comm>
        <low_level_comm>
          <checksum>true</checksum>
          <send_msg>sctk_network_send_message_default</send_msg>
          <notify_recv_msg>sctk_network_notify_recv_message_default</notify_recv_msg>
          <notify_matching_msg>sctk_network_notify_matching_message_default</notify_matching_msg>
          <notify_perform_msg>sctk_network_notify_perform_message_default</notify_perform_msg>
          <notify_idle_msg>sctk_network_notify_idle_message_default</notify_idle_msg>
          <notify_any_src_msg>sctk_network_notify_any_source_message_default</notify_any_src_msg>
          <network_mode>default</network_mode>
          <dyn_reordering>false</dyn_reordering>
        </low_level_comm>
        <mpc>
          <log_debug>false</log_debug>
          <hard_checking>false</hard_checking>
          <buffering>false</buffering>
        </mpc>
        <openmp>
          <vp>0</vp>
          <schedule>static</schedule>
          <nb_threads>0</nb_threads>
          <adjustment>false</adjustment>
          <nested>false</nested>
          <max_threads>64</max_threads>
          <max_alive_for_dyn>7</max_alive_for_dyn>
          <max_alive_for_guided>3</max_alive_for_guided>
          <max_alive_sections>3</max_alive_sections>
          <max_alive_single>3</max_alive_single>
        </openmp>
        <profiler>
          <file_prefix>mpc_profile</file_prefix>
          <append_date>true</append_date>
          <color_stdout>true</color_stdout>
          <level_colors>
            <level>#3A4D85</level>
            <level>#82A2FF</level>
            <level>#B8BDCB</level>
            <level>#5D6782</level>
            <level>#838383</level>
            <level>#5A5757</level>
          </level_colors>
        </profiler>
        <thread>
          <spin_delay>10</spin_delay>
          <interval>10</interval>
          <kthread_stack_size>10 MB</kthread_stack_size>
        </thread>
      </modules>
    </profile>
    <profile>
      <name>test</name>
      <modules>
        <allocator>
          <numa>false</numa>
          <keep_mem>5 MB</keep_mem>
          <keep_max>120 PB</keep_max>
        </allocator>
      </modules>
    </profile>
    <profile>
      <name>debug</name>
      <modules>
        <launcher>
          <verbosity>2</verbosity>
        </launcher>
      </modules>
    </profile>
  </profiles>
  <mappings>
    <mapping>
      <selectors>
        <env name='MPC_DEBUG'>true</env>
        <env name='MPC_GDB'>gdb</env>
      </selectors>
      <profiles>
        <profile>debug</profile>
      </profiles>
    </mapping>
    <mapping>
      <selectors>
        <env name='MPC_TEST'>true</env>
      </selectors>
      <profiles>
        <profile>test</profile>
      </profiles>
    </mapping>
  </mappings>
</mpc>
