=== cea-hpc/mpc/mpc/MPC_Config/extra/config-meta.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT config (usertypes?,modules?,validators?)>

<!ELEMENT usertypes ((struct|union)+)>

<!ELEMENT struct ((param|array)+)>
	<!ATTLIST struct name CDATA #REQUIRED>
	<!ATTLIST struct doc CDATA #REQUIRED>

<!ELEMENT param EMPTY>
	<!ATTLIST param name CDATA #REQUIRED>
	<!ATTLIST param type CDATA #REQUIRED>
	<!ATTLIST param doc CDATA #REQUIRED>
	<!ATTLIST param default CDATA #IMPLIED>

<!ELEMENT union (choice+)>
	<!ATTLIST union name CDATA #REQUIRED>
	<!ATTLIST union doc CDATA #REQUIRED>

<!ELEMENT choice EMPTY>
	<!ATTLIST choice name CDATA #REQUIRED>
	<!ATTLIST choice type CDATA #REQUIRED>

<!ELEMENT array (default?)>
	<!ATTLIST array name CDATA #REQUIRED>
	<!ATTLIST array entry-name CDATA #REQUIRED>
	<!ATTLIST array type CDATA #REQUIRED>
	<!ATTLIST array doc CDATA #REQUIRED>

<!ELEMENT default (value+)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT modules (module+)>

<!ELEMENT module EMPTY>
	<!ATTLIST module name CDATA #REQUIRED>
	<!ATTLIST module type CDATA #REQUIRED>

<!ELEMENT validators (handler+)>

<!ELEMENT handler (#PCDATA)>

=== cea-hpc/mpc/mpcframework/MPC_OpenMP/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>

            <enum name="mpcomp_task_larceny_mode_t" doc="">
	            <value>MPCOMP_TASK_LARCENY_MODE_HIERARCHICAL</value>
	            <value>MPCOMP_TASK_LARCENY_MODE_RANDOM</value>
	            <value>MPCOMP_TASK_LARCENY_MODE_RANDOM_ORDER</value>
	            <value>MPCOMP_TASK_LARCENY_MODE_ROUNDROBIN</value>
	            <value>MPCOMP_TASK_LARCENY_MODE_PRODUCER</value>
	            <value>MPCOMP_TASK_LARCENY_MODE_PRODUCER_ORDER</value>
	            <value>MPCOMP_TASK_LARCENY_MODE_COUNT</value>
            </enum>

            <enum name="mpcomp_task_larceny_mode" doc="">
		<struct name="openmp" doc="Options for MPC OpenMP.">
			<param name="vp" type="int" default="0" doc="Number of VPs for each OpenMP team"/>
			<param name="schedule" type="string" default="static" doc="Runtime schedule type and chunck size"/>
			<param name="nb_threads" type="int" doc="Number of threads to use during execution"/>
			<param name="adjustment" type="bool" default="false" doc="Dynamic adjustment of the number of threads"/>
			<param name="proc_bind" type="bool" default="true" doc="Bind threads to processor core"/>
			<param name="nested" type="bool" default="false" doc="Nested parallelism"/>
			<param name="stack_size" type="int" default="0" doc="Stack size for OpenMP threads"/>
			<param name="wait_policy" type="int" default="0" doc="Behavior of threads while waiting"/>
			<param name="thread_limit" type="int" default="0" doc="Maximum number of OpenMP threads among all teams"/>
			<param name="max_active_levels" type="int" default="0" doc="Maximum depth of nested parallelism"/>
			<param name="tree" type="string" default="" doc="Tree shape for OpenMP construct"/>
			<param name="max_threads" type="int" default="64" doc="Maximum number of threads for each team of a parallel region"/>
			<param name="max_alive_for_dyn" type="int" default="7" doc="Maximum number of shared for loops w/ dynamic schedule alive"/>
			<param name="max_alive_for_guided" type="int" default="3" doc="Maximum number of shared for loops w/ guided schedule alive"/>
			<param name="max_alive_sections" type="int" default="3" doc="Maximum number of alive sections construct"/>
			<param name="max_alive_single" type="int" default="3" doc="Maximum number of alive single construct"/>
			<param name="warn_nested" type="bool" default="false" doc="Emit warning when entering nested parallelism"/>
			<param name="mode" type="string" default="simple-mixed" doc="MPI/OpenMP hybrid mode (simple-mixed, alternating)"/>
			<param name="affinity" type="string" default="compact" doc="Affinity of threads for parallel regions (COMPACT, SCATTER, BALANCED)"/>
            
		</struct>
	</usertypes>
	<modules>
		<module name="openmp" type="openmp"/>
	</modules>
</config>

=== cea-hpc/mpc/mpcframework/MPC_Accelerators/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="accl_cuda" doc="CUDA-specific configuration">
			<param name="enabled" type="bool" default="false" doc="Set to true to enable CUDA context-switch" />
		</struct>
		<struct name="accl_openacc" doc="OpenACC-specific configuration">
			<param name="enabled" type="bool" default="false" doc="Set to true to enable OpenACC in MPC" />
		</struct>
		<struct name="accl_opencl" doc="OpenCL-specific configuration">
			<param name="enabled" type="bool" default="false" doc="Set to true to enable OpenCL in MPC" />
		</struct>

		<struct name="accl" doc="Options for MPC Accelerators module.">
			<param name="enabled" type="bool" default="false" doc="Set to true to enable Accelerators support" />
			<param name="cuda" type="accl_cuda" doc="Define CUDA-specific configuration" />
			<param name="openacc" type="accl_openacc" doc="Define OpenACC-specific configuration" />
			<param name="opencl" type="accl_opencl" doc="Define OpenCL-specific configuration" />
		</struct>
	</usertypes>
	<modules>
		<module name="accelerator" type="accl"/>
	</modules>
</config>
