=== cea-hpc/mpc/mpc/MPC_Config/extra/config-meta.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT config (usertypes?,modules?,validators?)>

<!ELEMENT usertypes ((struct|union)+)>

<!ELEMENT struct ((param|array)+)>
	<!ATTLIST struct name CDATA #REQUIRED>
	<!ATTLIST struct doc CDATA #REQUIRED>

<!ELEMENT param EMPTY>
	<!ATTLIST param name CDATA #REQUIRED>
	<!ATTLIST param type CDATA #REQUIRED>
	<!ATTLIST param doc CDATA #REQUIRED>
	<!ATTLIST param default CDATA #IMPLIED>

<!ELEMENT union (choice+)>
	<!ATTLIST union name CDATA #REQUIRED>
	<!ATTLIST union doc CDATA #REQUIRED>

<!ELEMENT choice EMPTY>
	<!ATTLIST choice name CDATA #REQUIRED>
	<!ATTLIST choice type CDATA #REQUIRED>

<!ELEMENT array (default?)>
	<!ATTLIST array name CDATA #REQUIRED>
	<!ATTLIST array entry-name CDATA #REQUIRED>
	<!ATTLIST array type CDATA #REQUIRED>
	<!ATTLIST array doc CDATA #REQUIRED>

<!ELEMENT default (value+)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT modules (module+)>

<!ELEMENT module EMPTY>
	<!ATTLIST module name CDATA #REQUIRED>
	<!ATTLIST module type CDATA #REQUIRED>

<!ELEMENT validators (handler+)>

<!ELEMENT handler (#PCDATA)>

=== cea-hpc/mpc/mpc/MPC_OpenMP/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="openmp" doc="Options for MPC OpenMP.">
			<param name="vp" type="int" doc="Number of VPs for each OpenMP team"/>
			<param name="schedule" type="string" default="static" doc="Runtime schedule type and chunck size"/>
			<param name="nb_threads" type="int" doc="Number of threads to use during execution"/>
			<param name="adjustment" type="bool" default="false" doc="Dynamic adjustment of the number of threads"/>
			<param name="nested" type="bool" default="false" doc="Nested parallelism"/>
			<param name="max_threads" type="int" default="64" doc="Maximum number of threads for each team of a parallel region"/>
			<param name="max_alive_for_dyn" type="int" default="7" doc="Maximum number of shared for loops w/ dynamic schedule alive"/>
			<param name="max_alive_for_guided" type="int" default="3" doc="Maximum number of shared for loops w/ guided schedule alive"/>
			<param name="max_alive_sections" type="int" default="3" doc="Maximum number of alive sections construct"/>
			<param name="max_alive_single" type="int" default="3" doc="Maximum number of alive single construct"/>
		</struct>
	</usertypes>
	<modules>
		<module name="openmp" type="openmp"/>
	</modules>
</config>

=== cea-hpc/mpc/mpcframework/MPC_Launch/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="launcher" doc="Options for MPC launcher.">
			<param name="verbosity" type="int" default="0" doc="Default verbosity level from 0 to 3. Can be override by -vv on mpcrun." alias="LN_VERBOSITY" />
			<param name="banner" type="bool" default="true" doc="Display the MPC banner at launch time to print some informations about the topology. Can be override by MPC_DISABLE_BANNER." alias="LN_BANNER" />
			<param name="autokill" type="int" default="0" doc="Automatically kill the MPC processes after a given timeout. Use 0 to disable. Can be override by MPC_AUTO_KILL_TIMEOUT." alias="LN_AUTOKILL" />
			<param name="user_launchers" type="string" default="default" doc="Permit to extend the launchers available via 'mpcrun -l=...' by providing scripts (named mpcrun_XXXX) in a user directory. Can be override by MPC_USER_LAUNCHERS."/>
			<param name="keep_rand_addr" type="bool" default="true" doc="Activate randomization of base addresses" />
			<param name="disable_rand_addr" type="bool" default="false" doc="Deactivate randomization of base addresses" alias="LN_ADDR_RAND_DISABLE" />
			<param name="disable_mpc" type="bool" default="false" doc="Do not use mpc for execution (deprecated?)" alias="LN_DISABLE_MPC"/>
            <param name="thread_init" type="funcptr" doc="Initialize multithreading mode" default="sctk_use_ethread_mxn" />
			<param name="nb_task" type="int" default="1" doc="Define the number of MPI tasks" alias="LN_MPI_TASK" />
			<param name="nb_process" type="int" default="1" doc="Define the number of MPC processes" alias="LN_MPC_PROCESS" />
			<param name="nb_processor" type="int" default="0" doc="Define the number of virtual processors" alias="LN_MPC_VP" />
			<param name="nb_node" type="int" default="1" doc="Define the number of compute nodes" alias="LN_MPC_NODE" />
			<param name="launcher" type="string" default="none" doc="Define which launcher to use" />
			<param name="max_try" type="int" default="10" doc="Define the max number of tries to access the topology file before failing" alias="LN_MAX_TOPO_TRY" />
			<param name="profiling" type="string" default="stdout" doc="Select the type of outputs for the profiling" />
			<param name="enable_smt" type="bool" default="false" doc="Enable usage of hyperthreaded cores if available on current architecture." alias="LN_ENABLE_SMT" />
			<param name="share_node" type="bool" default="false" doc="Enable the restriction on CPU number to share node" alias="LN_SHARE_NODE" />
			<param name="restart" type="bool" default="false" doc="Restart MPC from a previous checkpoint" alias="LN_RESTART" />
			<param name="checkpoint" type="bool" default="false" doc="Enable MPC checkpointing" alias="LN_CHECKPOINT" />
			<param name="report" type="bool" default="false" doc="Enable reporting." alias="LN_REPORT" />
		</struct>
	</usertypes>
	<modules>
		<module name="launcher" type="launcher"/>
	</modules>
</config>

=== cea-hpc/mpc/mpc/MPC_Common/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="launcher" doc="Options for MPC launcher.">
			<param name="smt" type="bool" default="false" doc="Enable usage of hyperthreaded cores if available on current architecture."/>
			<param name="cores" type="int" default="1" doc="Default number of cores if -c=X is not given to mpcrun."/>
			<param name="verbosity" type="int" default="0" doc="Default verbosity level from 0 to 3. Can be override by -vv on mpcrun."/>
			<param name="banner" type="bool" default="true" doc="Display the MPC banner at launch time to print some informations about the topology. Can be override by MPC_DISABLE_BANNER."/>
			<param name="autokill" type="int" default="0" doc="Automatically kill the MPC processes after a given timeout. Use 0 to disable. Can be override by MPC_AUTO_KILL_TIMEOUT."/>
			<param name="user_launchers" type="string" default="" doc="Permit to extend the launchers available via 'mpcrun -l=...' by providing scripts (named mpcrun_XXXX) in a user directory. Can be override by MPC_USER_LAUNCHERS."/>
			<param name="keep_rand_addr" type="bool" default="true" doc=""/>
			<param name="disable_rand_addr" type="bool" default="false" doc=""/>
			<param name="disable_mpc" type="bool" default="false" doc=""/>
			<param name="startup_args" type="string" default="" doc=""/>
			<param name="thread_init" type="funcptr" doc="" default="sctk_use_ethread_mxn"/>
			<param name="nb_task" type="int" default="1" doc=""/>
			<param name="nb_process" type="int" default="1" doc=""/>
			<param name="nb_processor" type="int" default="0" doc=""/>
			<param name="nb_node" type="int" default="0" doc=""/>
			<param name="launcher" type="string" default="none" doc=""/>
			<param name="max_try" type="int" default="10" doc=""/>
			<param name="vers_details" type="bool" default="false" doc=""/>
			<param name="profiling" type="string" default="none" doc=""/>
			<param name="enable_smt" type="bool" default="false" doc=""/>
			<param name="share_node" type="bool" default="false" doc=""/>
			<param name="restart" type="bool" default="false" doc=""/>
			<param name="checkpoint" type="bool" default="false" doc=""/>
			<param name="migration" type="bool" default="false" doc=""/>
		</struct>
		
		<struct name="debugger" doc="Options for MPC Debugger">
			<param name="colors" type="bool" default="true" doc="Print colored text in terminal"/>
			<param name="max_filename_size" type="int" default="1024" doc=""/>
		</struct>
	</usertypes>
	<modules>
		<module name="launcher" type="launcher"/>
		<module name="debugger" type="debugger"/>
	</modules>
</config>

=== cea-hpc/mpc/src/MPC_Threads/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="thread" doc="Options for MPC threads.">
			<param name="spin_delay" type="int" default="10" doc="Max number of accesses to the lock before calling thread_yield"/>
			<param name="interval" type="int" default="10" doc=""/>
			<param name="kthread_stack_size" type="size" default="10MB" doc="Define the stack size of MPC user threads"/>
			<param name="placement_policy" type="funcptr" doc="Initialize thread placement policy" default="mpc_thread_get_task_placement_and_count_default"/>
		</struct>
        <struct name="scheduler" doc="Scheduler priority parameters">
            <param name="timestamp_threshold" type="double" default="0.0" doc="Threshold for priority scheduling quantum"/>

            <param name="task_polling_thread_basic_priority" type="int" default="20" doc="Basic priority of polling tasks"/>
            <param name="task_polling_thread_basic_priority_step" type="int" default="20" doc="Step of basic priority of polling tasks"/>
            <param name="task_polling_thread_current_priority_step" type="int" default="20" doc="Step of current priority of polling tasks"/>

            <param name="sched_NBC_Pthread_basic_priority" type="int" default="20" doc="Basic priority of polling tasks"/>
            <param name="sched_NBC_Pthread_basic_priority_step" type="int" default="20" doc="Step of basic priority of nbc progress threads"/>
            <param name="sched_NBC_Pthread_current_priority_step" type="int" default="20" doc="Step of current priority of nbc progress threads"/>

            <param name="mpi_basic_priority" type="int" default="20" doc="Basic priority of MPI threads"/>
            <param name="omp_basic_priority" type="int" default="20" doc="Basic priority of OMP threads"/>
            <param name="posix_basic_priority" type="int" default="20" doc="Basic priority of POSIX threads"/>
            <param name="progress_basic_priority" type="int" default="20" doc="Basic priority of POSIX threads"/>
        </struct>
	<struct name="accl_cuda" doc="CUDA-specific configuration">
		<param name="enabled" type="bool" default="false" doc="Set to true to enable CUDA context-switch" />
	</struct>
	<struct name="accl_openacc" doc="OpenACC-specific configuration">
		<param name="enabled" type="bool" default="false" doc="Set to true to enable OpenACC in MPC" />
	</struct>
	<struct name="accl_opencl" doc="OpenCL-specific configuration">
		<param name="enabled" type="bool" default="false" doc="Set to true to enable OpenCL in MPC" />
	</struct>

	<struct name="accl" doc="Options for MPC Accelerators module.">
		<param name="enabled" type="bool" default="false" doc="Set to true to enable Accelerators support" />
		<param name="cuda" type="accl_cuda" doc="Define CUDA-specific configuration" />
		<param name="openacc" type="accl_openacc" doc="Define OpenACC-specific configuration" />
		<param name="opencl" type="accl_opencl" doc="Define OpenCL-specific configuration" />
	</struct>
	</usertypes>
	<modules>
		<module name="thread" type="thread"/>
		<module name="scheduler" type="scheduler"/>
		<module name="accelerator" type="accl"/>
	</modules>
</config>

=== cea-hpc/mpc/mpc/MPC_Profiler/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="profiler"     doc="Options for the internal MPC Profiler">
			<param name="file_prefix"   type="string" default="mpc_profile" doc="Prefix of MPC Profiler outputs"/>
			<param name="append_date"   type="bool" default="true" doc="Add a timestamp to profiles file names"/>
			<param name="color_stdout"   type="bool" default="true" doc="Profile in color when outputed to stdout"/>
			
			<array name="level_colors" entry-name="level" type="string" doc="Color for levels of profiler output">
				<default>
					<value>"#3A4D85"</value>
					<value>"#82A2FF"</value>
					<value>"#B8BDCB"</value>
					<value>"#5D6782"</value>
					<value>"#838383"</value>
					<value>"#5A5757"</value>
				</default>
			</array>
		</struct>
	</usertypes>
	<modules>
		<module name="profiler" type="profiler"/>
	</modules>
	<validators>
		<handler>sctk_runtime_config_empty_validator_for_test</handler>
	</validators>
</config>

=== cea-hpc/mpc/mpcframework/MPC_Threads/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="thread" doc="Options for MPC threads.">
			<param name="spin_delay" type="int" default="10" doc="Max number of accesses to the lock before calling thread_yield"/>
			<param name="interval" type="int" default="10" doc=""/>
			<param name="kthread_stack_size" type="size" default="10MB" doc="Define the stack size of MPC user threads"/>
		</struct>
	</usertypes>
	<modules>
		<module name="thread" type="thread"/>
	</modules>
</config>

=== cea-hpc/mpc/mpcframework/MPC_Common/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="debugger" doc="Options for MPC Debugger">
			<param name="colors" type="bool" default="true" doc="Print colored text in terminal"/>
			<param name="max_filename_size" type="int" default="1024" doc=""/>
			<param name="mpc_bt_sig" type="int" default="1" doc="Should MPC capture common signals also connected to the MPC_BT_SIG environment variable which supersedes the config" />
		</struct>
	</usertypes>
	<modules>
		<module name="debugger" type="debugger"/>
	</modules>
</config>

=== cea-hpc/mpc/mpcframework/MPC_MPI/config-meta.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "../MPC_Config/extra/config-meta.dtd">
<config>
	<usertypes>
		<struct name="collectives_intra" doc="Collectives intracom MPI">
            <param name="barrier_intra" type="funcptr" default="__INTERNAL__PMPI_Barrier_intra" doc="MPI_Barrier intracom algorithm"/>
            <param name="bcast_intra" type="funcptr" default="__INTERNAL__PMPI_Bcast_intra" doc="Type of MPI_Bcast intracom algorithm"/>
            <param name="allgather_intra" type="funcptr" default="__INTERNAL__PMPI_Allgather_intra" doc="MPI_Allgather intracom algorithm"/>
            <param name="allgatherv_intra" type="funcptr" default="__INTERNAL__PMPI_Allgatherv_intra" doc="MPI_Allgatherv intracom algorithm"/>
            <param name="alltoall_intra" type="funcptr" default="__INTERNAL__PMPI_Alltoall_intra" doc="MPI_Alltoall intracom algorithm"/>
            <param name="alltoallv_intra" type="funcptr" default="__INTERNAL__PMPI_Alltoallv_intra" doc="Alltoallv intracom algorithm"/>
            <param name="alltoallw_intra" type="funcptr" default="__INTERNAL__PMPI_Alltoallw_intra" doc="MPI_Alltoallw intracom algorithm"/>
            <param name="gather_intra" type="funcptr" default="__INTERNAL__PMPI_Gather_intra" doc="MPI_Gather intracom algorithm"/>
            <param name="gatherv_intra" type="funcptr" default="__INTERNAL__PMPI_Gatherv_intra" doc="MPI_Gatherv intracom algorithm"/>
            <param name="scatter_intra" type="funcptr" default="__INTERNAL__PMPI_Scatter_intra" doc="MPI_Scatter intracom algorithm"/>
            <param name="scatterv_intra" type="funcptr" default="__INTERNAL__PMPI_Scatterv_intra" doc="MPI_Scatterv intracom algorithm"/>
            <param name="scan_intra" type="funcptr" default="__INTERNAL__PMPI_Scan_intra" doc="MPI_Scan intracom algorithm"/>
            <param name="exscan_intra" type="funcptr" default="__INTERNAL__PMPI_Exscan_intra" doc="MPI_Exscan intracom algorithm"/>
            <param name="reduce_intra" type="funcptr" default="__INTERNAL__PMPI_Reduce_intra" doc="MPI_Reduce intracom algorithm"/>
            <param name="allreduce_intra" type="funcptr" default="__INTERNAL__PMPI_Allreduce_intra" doc="MPI_Allreduce intracom algorithm"/>
            <param name="reduce_scatter_intra" type="funcptr" default="__INTERNAL__PMPI_Reduce_scatter_intra" doc="MPI_Reduce_scatter intracom algorithm"/>
            <param name="reduce_scatter_block_intra" type="funcptr" default="__INTERNAL__PMPI_Reduce_scatter_block_intra" doc="MPI_Reduce_scatter_block intracom algorithm"/>
        </struct>

        <struct name="collectives_inter" doc="Collectives intercom MPI">
            <param name="barrier_inter" type="funcptr" default="__INTERNAL__PMPI_Barrier_inter" doc="MPI_Barrier intercom algorithm"/><param name="bcast_inter" type="funcptr" default="__INTERNAL__PMPI_Bcast_inter" doc="MPI_Barrier intercom algorithm"/>
            <param name="allgather_inter" type="funcptr" default="__INTERNAL__PMPI_Allgather_inter" doc="MPI_Allgather intercom algorithm"/>
            <param name="allgatherv_inter" type="funcptr" default="__INTERNAL__PMPI_Allgatherv_inter" doc="MPI_Allgatherv intercom algorithm"/>
            <param name="alltoall_inter" type="funcptr" default="__INTERNAL__PMPI_Alltoall_inter" doc="MPI_Alltoall intercom algorithm"/>
            <param name="alltoallv_inter" type="funcptr" default="__INTERNAL__PMPI_Alltoallv_inter" doc="MPI_Alltoallv intercom algorithm"/>
            <param name="alltoallw_inter" type="funcptr" default="__INTERNAL__PMPI_Alltoallw_inter" doc="MPI_Alltoallw intercom algorithm"/>
            <param name="gather_inter" type="funcptr" default="__INTERNAL__PMPI_Gather_inter" doc="MPI_Gather intercom algorithm"/>
            <param name="gatherv_inter" type="funcptr" default="__INTERNAL__PMPI_Gatherv_inter" doc="MPI_Gatherv intercom algorithm"/>
            <param name="scatter_inter" type="funcptr" default="__INTERNAL__PMPI_Scatter_inter" doc="MPI_Scatter intercom algorithm"/>
            <param name="scatterv_inter" type="funcptr" default="__INTERNAL__PMPI_Scatterv_inter" doc="MPI_Scatterv intercom algorithm"/>
            <param name="reduce_inter" type="funcptr" default="__INTERNAL__PMPI_Reduce_inter" doc="MPI_Reduce intercom algorithm"/>
            <param name="allreduce_inter" type="funcptr" default="__INTERNAL__PMPI_Allreduce_inter" doc="MPI_Allreduce intercom algorithm"/>
            <param name="reduce_scatter_inter" type="funcptr" default="__INTERNAL__PMPI_Reduce_scatter_inter" doc="MPI_Reduce_scatter intercom algorithm"/>
            <param name="reduce_scatter_block_inter" type="funcptr" default="__INTERNAL__PMPI_Reduce_scatter_block_inter" doc="MPI_Reduce_scatter_block intercom algorithm"/>
        </struct>

	<struct name="progress_thread" doc="Progress thread NBC">
	    <param name="use_progress_thread" type="int" default="0" doc="If use progress threads for non blocking collectives"/>
	</struct>
	</usertypes>
	<modules>
		<module name="collectives_intra" type="collectives_intra"/>
        	<module name="collectives_inter" type="collectives_inter"/>
        	<module name="progress_thread" type="progress_thread"/>
	</modules>
</config>
